# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import test_agent_pb2 as proto_dot_test__agent__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/test_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DutAgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAgentDetails = channel.unary_unary(
            '/dutTestAgent.DutAgentService/GetAgentDetails',
            request_serializer=proto_dot_test__agent__pb2.GetAgentDetailsRequest.SerializeToString,
            response_deserializer=proto_dot_test__agent__pb2.GetAgentDetailsResponse.FromString,
            _registered_method=True)
        self.RunCommand = channel.unary_unary(
            '/dutTestAgent.DutAgentService/RunCommand',
            request_serializer=proto_dot_test__agent__pb2.RunCommandRequest.SerializeToString,
            response_deserializer=proto_dot_test__agent__pb2.RunCommandResponse.FromString,
            _registered_method=True)
        self.GetDeviceInfo = channel.unary_unary(
            '/dutTestAgent.DutAgentService/GetDeviceInfo',
            request_serializer=proto_dot_test__agent__pb2.GetDeviceInfoRequest.SerializeToString,
            response_deserializer=proto_dot_test__agent__pb2.GetDeviceInfoResponse.FromString,
            _registered_method=True)
        self.StreamExecutionLogs = channel.unary_stream(
            '/dutTestAgent.DutAgentService/StreamExecutionLogs',
            request_serializer=proto_dot_test__agent__pb2.StreamExecutionLogsRequest.SerializeToString,
            response_deserializer=proto_dot_test__agent__pb2.LogEntry.FromString,
            _registered_method=True)
        self.ConfigureOLEDDisplay = channel.unary_unary(
            '/dutTestAgent.DutAgentService/ConfigureOLEDDisplay',
            request_serializer=proto_dot_test__agent__pb2.OLEDSettings.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True)
        self.SetOLEDStaticText = channel.unary_unary(
            '/dutTestAgent.DutAgentService/SetOLEDStaticText',
            request_serializer=proto_dot_test__agent__pb2.SetOLEDTextRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True)
        self.SetOLEDScrollingText = channel.unary_unary(
            '/dutTestAgent.DutAgentService/SetOLEDScrollingText',
            request_serializer=proto_dot_test__agent__pb2.SetOLEDTextRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True)
        self.ConfigureBattery = channel.unary_unary(
            '/dutTestAgent.DutAgentService/ConfigureBattery',
            request_serializer=proto_dot_test__agent__pb2.BatterySettings.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True)
        self.GetBatteryReadings = channel.unary_unary(
            '/dutTestAgent.DutAgentService/GetBatteryReadings',
            request_serializer=proto_dot_test__agent__pb2.GetBatteryReadingsRequest.SerializeToString,
            response_deserializer=proto_dot_test__agent__pb2.GetBatteryReadingsResponse.FromString,
            _registered_method=True)
        self.DiscoverEventDevices = channel.unary_unary(
            '/dutTestAgent.DutAgentService/DiscoverEventDevices',
            request_serializer=proto_dot_test__agent__pb2.DiscoverEventDevicesRequest.SerializeToString,
            response_deserializer=proto_dot_test__agent__pb2.DiscoverEventDevicesResponse.FromString,
            _registered_method=True)
        self.GetEventReportOverDuration = channel.unary_unary(
            '/dutTestAgent.DutAgentService/GetEventReportOverDuration',
            request_serializer=proto_dot_test__agent__pb2.GetEventReportOverDurationRequest.SerializeToString,
            response_deserializer=proto_dot_test__agent__pb2.GetEventReportOverDurationResponse.FromString,
            _registered_method=True)
        self.ConfigureBuzzer = channel.unary_unary(
            '/dutTestAgent.DutAgentService/ConfigureBuzzer',
            request_serializer=proto_dot_test__agent__pb2.BuzzerSettings.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True)
        self.SetBuzzer = channel.unary_unary(
            '/dutTestAgent.DutAgentService/SetBuzzer',
            request_serializer=proto_dot_test__agent__pb2.SetBuzzerRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True)
        self.GetSystemState = channel.unary_unary(
            '/dutTestAgent.DutAgentService/GetSystemState',
            request_serializer=proto_dot_test__agent__pb2.GetSystemStateRequest.SerializeToString,
            response_deserializer=proto_dot_test__agent__pb2.GetSystemStateResponse.FromString,
            _registered_method=True)
        self.UploadFile = channel.stream_unary(
            '/dutTestAgent.DutAgentService/UploadFile',
            request_serializer=proto_dot_test__agent__pb2.UploadFileRequest.SerializeToString,
            response_deserializer=proto_dot_test__agent__pb2.UploadFileResponse.FromString,
            _registered_method=True)
        self.DownloadFile = channel.unary_stream(
            '/dutTestAgent.DutAgentService/DownloadFile',
            request_serializer=proto_dot_test__agent__pb2.DownloadFileRequest.SerializeToString,
            response_deserializer=proto_dot_test__agent__pb2.DownloadFileResponse.FromString,
            _registered_method=True)


class DutAgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAgentDetails(self, request, context):
        """GetAgentDetails retrieves basic identification and status information about the agent.
        This can be used as a simple health check and to verify agent connectivity.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceInfo(self, request, context):
        """GetDeviceInfo retrieves basic identification and status information about the DUT.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamExecutionLogs(self, request, context):
        """StreamExecutionLogs enables server-side streaming of execution logs from the agent to the client.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureOLEDDisplay(self, request, context):
        """ConfigureOLEDDisplay sets the configuration for the OLED display.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetOLEDStaticText(self, request, context):
        """SetOLEDStaticText displays a static text message on the OLED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetOLEDScrollingText(self, request, context):
        """SetOLEDScrollingText displays a scrolling text message on the OLED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureBattery(self, request, context):
        """ConfigureBattery sets the configuration for battery readings.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBatteryReadings(self, request, context):
        """GetBatteryReadings retrieves the current battery readings.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverEventDevices(self, request, context):
        """DiscoverEventDevices scans for available input event devices.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventReportOverDuration(self, request, context):
        """GetEventReportOverDuration captures and reports input events for a specified duration as a CSV string.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureBuzzer(self, request, context):
        """ConfigureBuzzer sets the device path for the buzzer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBuzzer(self, request, context):
        """SetBuzzer turns the buzzer on or off.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemState(self, request, context):
        """GetSystemState retrieves various system related information (CPU, memory, serial).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request_iterator, context):
        """UploadFile allows client to upload a file to the agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """DownloadFile allows client to download a file from the agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DutAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetAgentDetails': grpc.unary_unary_rpc_method_handler(
            servicer.GetAgentDetails,
            request_deserializer=proto_dot_test__agent__pb2.GetAgentDetailsRequest.FromString,
            response_serializer=proto_dot_test__agent__pb2.GetAgentDetailsResponse.SerializeToString,
        ),
        'RunCommand': grpc.unary_unary_rpc_method_handler(
            servicer.RunCommand,
            request_deserializer=proto_dot_test__agent__pb2.RunCommandRequest.FromString,
            response_serializer=proto_dot_test__agent__pb2.RunCommandResponse.SerializeToString,
        ),
        'GetDeviceInfo': grpc.unary_unary_rpc_method_handler(
            servicer.GetDeviceInfo,
            request_deserializer=proto_dot_test__agent__pb2.GetDeviceInfoRequest.FromString,
            response_serializer=proto_dot_test__agent__pb2.GetDeviceInfoResponse.SerializeToString,
        ),
        'StreamExecutionLogs': grpc.unary_stream_rpc_method_handler(
            servicer.StreamExecutionLogs,
            request_deserializer=proto_dot_test__agent__pb2.StreamExecutionLogsRequest.FromString,
            response_serializer=proto_dot_test__agent__pb2.LogEntry.SerializeToString,
        ),
        'ConfigureOLEDDisplay': grpc.unary_unary_rpc_method_handler(
            servicer.ConfigureOLEDDisplay,
            request_deserializer=proto_dot_test__agent__pb2.OLEDSettings.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'SetOLEDStaticText': grpc.unary_unary_rpc_method_handler(
            servicer.SetOLEDStaticText,
            request_deserializer=proto_dot_test__agent__pb2.SetOLEDTextRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'SetOLEDScrollingText': grpc.unary_unary_rpc_method_handler(
            servicer.SetOLEDScrollingText,
            request_deserializer=proto_dot_test__agent__pb2.SetOLEDTextRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'ConfigureBattery': grpc.unary_unary_rpc_method_handler(
            servicer.ConfigureBattery,
            request_deserializer=proto_dot_test__agent__pb2.BatterySettings.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'GetBatteryReadings': grpc.unary_unary_rpc_method_handler(
            servicer.GetBatteryReadings,
            request_deserializer=proto_dot_test__agent__pb2.GetBatteryReadingsRequest.FromString,
            response_serializer=proto_dot_test__agent__pb2.GetBatteryReadingsResponse.SerializeToString,
        ),
        'DiscoverEventDevices': grpc.unary_unary_rpc_method_handler(
            servicer.DiscoverEventDevices,
            request_deserializer=proto_dot_test__agent__pb2.DiscoverEventDevicesRequest.FromString,
            response_serializer=proto_dot_test__agent__pb2.DiscoverEventDevicesResponse.SerializeToString,
        ),
        'GetEventReportOverDuration': grpc.unary_unary_rpc_method_handler(
            servicer.GetEventReportOverDuration,
            request_deserializer=proto_dot_test__agent__pb2.GetEventReportOverDurationRequest.FromString,
            response_serializer=proto_dot_test__agent__pb2.GetEventReportOverDurationResponse.SerializeToString,
        ),
        'ConfigureBuzzer': grpc.unary_unary_rpc_method_handler(
            servicer.ConfigureBuzzer,
            request_deserializer=proto_dot_test__agent__pb2.BuzzerSettings.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'SetBuzzer': grpc.unary_unary_rpc_method_handler(
            servicer.SetBuzzer,
            request_deserializer=proto_dot_test__agent__pb2.SetBuzzerRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'GetSystemState': grpc.unary_unary_rpc_method_handler(
            servicer.GetSystemState,
            request_deserializer=proto_dot_test__agent__pb2.GetSystemStateRequest.FromString,
            response_serializer=proto_dot_test__agent__pb2.GetSystemStateResponse.SerializeToString,
        ),
        'UploadFile': grpc.stream_unary_rpc_method_handler(
            servicer.UploadFile,
            request_deserializer=proto_dot_test__agent__pb2.UploadFileRequest.FromString,
            response_serializer=proto_dot_test__agent__pb2.UploadFileResponse.SerializeToString,
        ),
        'DownloadFile': grpc.unary_stream_rpc_method_handler(
            servicer.DownloadFile,
            request_deserializer=proto_dot_test__agent__pb2.DownloadFileRequest.FromString,
            response_serializer=proto_dot_test__agent__pb2.DownloadFileResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'dutTestAgent.DutAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        'dutTestAgent.DutAgentService', rpc_method_handlers)

 # This class is part of an EXPERIMENTAL API.


class DutAgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAgentDetails(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dutTestAgent.DutAgentService/GetAgentDetails',
            proto_dot_test__agent__pb2.GetAgentDetailsRequest.SerializeToString,
            proto_dot_test__agent__pb2.GetAgentDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunCommand(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dutTestAgent.DutAgentService/RunCommand',
            proto_dot_test__agent__pb2.RunCommandRequest.SerializeToString,
            proto_dot_test__agent__pb2.RunCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceInfo(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dutTestAgent.DutAgentService/GetDeviceInfo',
            proto_dot_test__agent__pb2.GetDeviceInfoRequest.SerializeToString,
            proto_dot_test__agent__pb2.GetDeviceInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamExecutionLogs(request,
                            target,
                            options=(),
                            channel_credentials=None,
                            call_credentials=None,
                            insecure=False,
                            compression=None,
                            wait_for_ready=None,
                            timeout=None,
                            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dutTestAgent.DutAgentService/StreamExecutionLogs',
            proto_dot_test__agent__pb2.StreamExecutionLogsRequest.SerializeToString,
            proto_dot_test__agent__pb2.LogEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureOLEDDisplay(request,
                             target,
                             options=(),
                             channel_credentials=None,
                             call_credentials=None,
                             insecure=False,
                             compression=None,
                             wait_for_ready=None,
                             timeout=None,
                             metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dutTestAgent.DutAgentService/ConfigureOLEDDisplay',
            proto_dot_test__agent__pb2.OLEDSettings.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetOLEDStaticText(request,
                          target,
                          options=(),
                          channel_credentials=None,
                          call_credentials=None,
                          insecure=False,
                          compression=None,
                          wait_for_ready=None,
                          timeout=None,
                          metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dutTestAgent.DutAgentService/SetOLEDStaticText',
            proto_dot_test__agent__pb2.SetOLEDTextRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetOLEDScrollingText(request,
                             target,
                             options=(),
                             channel_credentials=None,
                             call_credentials=None,
                             insecure=False,
                             compression=None,
                             wait_for_ready=None,
                             timeout=None,
                             metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dutTestAgent.DutAgentService/SetOLEDScrollingText',
            proto_dot_test__agent__pb2.SetOLEDTextRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureBattery(request,
                         target,
                         options=(),
                         channel_credentials=None,
                         call_credentials=None,
                         insecure=False,
                         compression=None,
                         wait_for_ready=None,
                         timeout=None,
                         metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dutTestAgent.DutAgentService/ConfigureBattery',
            proto_dot_test__agent__pb2.BatterySettings.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBatteryReadings(request,
                           target,
                           options=(),
                           channel_credentials=None,
                           call_credentials=None,
                           insecure=False,
                           compression=None,
                           wait_for_ready=None,
                           timeout=None,
                           metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dutTestAgent.DutAgentService/GetBatteryReadings',
            proto_dot_test__agent__pb2.GetBatteryReadingsRequest.SerializeToString,
            proto_dot_test__agent__pb2.GetBatteryReadingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscoverEventDevices(request,
                             target,
                             options=(),
                             channel_credentials=None,
                             call_credentials=None,
                             insecure=False,
                             compression=None,
                             wait_for_ready=None,
                             timeout=None,
                             metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dutTestAgent.DutAgentService/DiscoverEventDevices',
            proto_dot_test__agent__pb2.DiscoverEventDevicesRequest.SerializeToString,
            proto_dot_test__agent__pb2.DiscoverEventDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEventReportOverDuration(request,
                                   target,
                                   options=(),
                                   channel_credentials=None,
                                   call_credentials=None,
                                   insecure=False,
                                   compression=None,
                                   wait_for_ready=None,
                                   timeout=None,
                                   metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dutTestAgent.DutAgentService/GetEventReportOverDuration',
            proto_dot_test__agent__pb2.GetEventReportOverDurationRequest.SerializeToString,
            proto_dot_test__agent__pb2.GetEventReportOverDurationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureBuzzer(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dutTestAgent.DutAgentService/ConfigureBuzzer',
            proto_dot_test__agent__pb2.BuzzerSettings.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBuzzer(request,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dutTestAgent.DutAgentService/SetBuzzer',
            proto_dot_test__agent__pb2.SetBuzzerRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemState(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dutTestAgent.DutAgentService/GetSystemState',
            proto_dot_test__agent__pb2.GetSystemStateRequest.SerializeToString,
            proto_dot_test__agent__pb2.GetSystemStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFile(request_iterator,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dutTestAgent.DutAgentService/UploadFile',
            proto_dot_test__agent__pb2.UploadFileRequest.SerializeToString,
            proto_dot_test__agent__pb2.UploadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFile(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dutTestAgent.DutAgentService/DownloadFile',
            proto_dot_test__agent__pb2.DownloadFileRequest.SerializeToString,
            proto_dot_test__agent__pb2.DownloadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
